-- Supabase SQL Editor'da çalıştır. Yeşillenen tile kayıtları burada tutulur.
-- Tıklanan noktanın tam 3D konumu (pos_x, pos_y, pos_z) kaydedilir; yenilemeden sonra yeşil aynı yerde kalır.

create table if not exists green_tiles (
  id bigint generated by default as identity primary key,
  x int not null,
  y int not null,
  pos_x double precision,
  pos_y double precision,
  pos_z double precision,
  tx_hash text,
  user_address text,
  created_at timestamptz default now()
);

-- Mevcut tabloda sütun yoksa ekle (bir kez çalıştır)
alter table green_tiles add column if not exists pos_x double precision;
alter table green_tiles add column if not exists pos_y double precision;
alter table green_tiles add column if not exists pos_z double precision;

create index if not exists green_tiles_xy on green_tiles (x, y);

-- RLS (isteğe bağlı): herkes okuyabilsin, sadece API yazabilsin (service role)
alter table green_tiles enable row level security;

drop policy if exists "Allow public read" on green_tiles;
create policy "Allow public read"
  on green_tiles for select
  using (true);

drop policy if exists "Service role can insert" on green_tiles;
create policy "Service role can insert"
  on green_tiles for insert
  with check (true);

-- Liderlik tablosu için doğru tx sayısı (tüm satırlar üzerinden GROUP BY)
create or replace function get_leaderboard(lim int default 20)
returns table(address text, count bigint)
language sql stable
as $$
  select lower(user_address)::text as address, count(*)::bigint as count
  from green_tiles
  where user_address is not null and trim(user_address) != ''
  group by lower(user_address)
  order by count desc
  limit lim;
$$;

-- Realtime (anlık güncelleme): Supabase Dashboard > Database > Realtime > "green_tiles" tablosunu ekle.
-- Veya SQL ile (bir kez): alter publication supabase_realtime add table green_tiles;
